In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(r'C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\data\raw\ipl.db')
def q(sql):
    return pd.read_sql_query(sql, conn)

In [2]:
q("""select * from venues ;""")

,venue_id,venue,city
0,1,M Chinnaswamy Stadium,Bangalore
1,2,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,3,Maharashtra Cricket Association Stadium,Pune
3,4,Saurashtra Cricket Association Stadium,Rajkot
4,5,Holkar Cricket Stadium,Indore
...,...,...,...
58,59,Subrata Roy Sahara Stadium,Pune
59,60,Shaheed Veer Narayan Singh International Stadium,Raipur
60,61,JSCA International Stadium Complex,Ranchi
61,62,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
62,63,Maharaja Yadavindra Singh International Cricke...,New Chandigarh

In [3]:
q(""" select * from matches;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [4]:
q("""select * from deliveries;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,1,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals

In [5]:
q("""select * from players;""")

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name
0,963,MN Samuels,Right hand Bat,Right arm Offbreak,,Marlon Nathaniel Samuels
1,53,SB Jakati,Left hand Bat,Slow Left arm Orthodox,,Shadab Bashir Jakati
2,12,DA Warner,Left hand Bat,Legbreak,,David Andrew Warner
3,268,RA Tripathi,Right hand Bat,Right arm Medium,,Rahul Ajay Tripathi
4,186,S Nadeem,Right hand Bat,Slow Left arm Orthodox,,Shahbaz Nadeem
...,...,...,...,...,...,...
794,8475,Suyash Sharma,Right hand Bat,Legbreak Googly,,Suyash Sharma
795,45004,D Madushanka,Right hand Bat,Right arm Medium fast,NaN,K Dasun Madusanka
796,42566,V Suryavanshi,Left hand Bat,Slow Left arm Orthodox,NaN,Vaibhav Suryavanshi
797,26,N Rana,Left hand Bat,"Right arm Medium, Right arm Offbreak, Legbreak",,Nitish Rana
798,45986,SU Parakh,Left hand Bat,Legbreak,NaN,Sahil Ulhas Parakh

In [6]:
q("""select * from teams;""")

    team_id                    team_name
0         1  Royal Challengers Bangalore
1         2          Sunrisers Hyderabad
2         3               Mumbai Indians
3         4       Rising Pune Supergiant
4         5                Gujarat Lions
5         6        Kolkata Knight Riders
6       129          Chennai Super Kings
7       134             Rajasthan Royals
8       252               Delhi Capitals
9       494                 Punjab Kings
10      614         Lucknow Super Giants
11      615               Gujarat Titans
12     1068              Deccan Chargers
13     1414         Kochi Tuskers Kerala
14     1419                Pune Warriors
15     3604      Rising Pune Supergiants

In [7]:
q("""select * from matches limit 15;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
5,1082595,2017,6,Bengaluru,2017-04-08,Indian Premier League,5.0,male,T20,T20,...,Royal Challengers Bangalore,15.0,NaN,win,KM Jadhav,1,252,1,1,4.0
6,1082596,2017,6,Hyderabad,2017-04-09,Indian Premier League,6.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,9.0,win,Rashid Khan,2,5,2,2,22.0
7,1082597,2017,6,Mumbai,2017-04-09,Indian Premier League,7.0,male,T20,T20,...,Mumbai Indians,NaN,4.0,win,N Rana,3,6,3,3,26.0
8,1082598,2017,6,Indore,2017-04-10,Indian Premier League,8.0,male,T20,T20,...,Punjab Kings,NaN,8.0,win,AR Patel,494,1,1,494,70.0
9,1082599,2017,6,Pune,2017-04-11,Indian Premier League,9.0,male,T20,T20,...,Delhi Capitals,97.0,NaN,win,SV Samson,4,252,4,252,180.0
10,1082600,2017,6,Mumbai,2017-04-12,Indian Premier League,10.0,male,T20,T20,...,Mumbai Indians,NaN,4.0,win,JJ Bumrah,3,2,3,3,33.0
11,1082601,2017,6,Kolkata,2017-04-13,Indian Premier League,11.0,male,T20,T20,...,Kolkata Knight Riders,NaN,8.0,win,SP Narine,6,494,6,6,65.0
12,1082602,2017,6,Bangalore,2017-04-14,Indian Premier League,12.0,male,T20,T20,...,Mumbai Indians,NaN,4.0,win,KA Pollard,1,3,3,3,29.0
13,1082603,2017,6,Rajkot,2017-04-14,Indian Premier League,13.0,male,T20,T20,...,Gujarat Lions,NaN,7.0,win,AJ Tye,5,4,5,5,351.0
14,1082604,2017,6,Kolkata,2017-04-15,Indian Premier League,14.0,male,T20,T20,...,Kolkata Knight Riders,17.0,NaN,win,RV Uthappa,6,2,2,6,58.0

In [8]:
q("""select match_id,city,venue from matches limit 15;""")

    match_id       city                                      venue
0     335982  Bangalore                      M Chinnaswamy Stadium
1    1082591  Hyderabad  Rajiv Gandhi International Stadium, Uppal
2    1082592       Pune    Maharashtra Cricket Association Stadium
3    1082593     Rajkot     Saurashtra Cricket Association Stadium
4    1082594     Indore                     Holkar Cricket Stadium
5    1082595  Bengaluru                      M.Chinnaswamy Stadium
6    1082596  Hyderabad  Rajiv Gandhi International Stadium, Uppal
7    1082597     Mumbai                           Wankhede Stadium
8    1082598     Indore                     Holkar Cricket Stadium
9    1082599       Pune    Maharashtra Cricket Association Stadium
10   1082600     Mumbai                           Wankhede Stadium
11   1082601    Kolkata                               Eden Gardens
12   1082602  Bangalore                      M Chinnaswamy Stadium
13   1082603     Rajkot     Saurashtra Cricket Association Stadium
14   1082604    Kolkata                               Eden Gardens

In [9]:
q(""" SELECT DISTINCT bowler_type from deliveries;""")

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [10]:
q(""" SELECT DISTINCT season from matches;""")

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [11]:
q(""" SELECT DISTINCT match_id from matches;""")

      match_id
0       335982
1      1082591
2      1082592
3      1082593
4      1082594
...        ...
1207   1529282
1208   1529283
1209   1529284
1210   1529285
1211   1529286

[1212 rows x 1 columns]

In [12]:
q("""SELECT match_id,season_id,city,match_winner
FROM matches
WHERE match_winner='Kolkata Knight Riders';""")

     match_id  season_id       city           match_winner
0      335982       2008  Bangalore  Kolkata Knight Riders
1     1082593       2017     Rajkot  Kolkata Knight Riders
2     1082601       2017    Kolkata  Kolkata Knight Riders
3     1082604       2017    Kolkata  Kolkata Knight Riders
4     1082608       2017      Delhi  Kolkata Knight Riders
..        ...        ...        ...                    ...
132   1473462       2025    Chennai  Kolkata Knight Riders
133   1473481       2025    Kolkata  Kolkata Knight Riders
134   1473485       2025      Delhi  Kolkata Knight Riders
135   1473490       2025    Kolkata  Kolkata Knight Riders
136   1529271       2026    Kolkata  Kolkata Knight Riders

[137 rows x 4 columns]

In [13]:
q("""SELECT match_id,city,venue 
FROM matches 
where season >= 2015;""")

,match_id,city,venue
0,829705,Kolkata,Eden Gardens
1,829707,Chennai,"MA Chidambaram Stadium, Chepauk"
2,829709,Pune,Maharashtra Cricket Association Stadium
3,829711,Chennai,"MA Chidambaram Stadium, Chepauk"
4,829713,Kolkata,Eden Gardens
...,...,...,...
749,1529282,Delhi,"Arun Jaitley Stadium, Delhi"
750,1529283,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
751,1529284,Mumbai,"Wankhede Stadium, Mumbai"
752,1529285,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
753,1529286,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [14]:
q("""SELECT match_id,city,venue 
FROM matches 
where season <= 2015;""")

     match_id        city                                       venue
0      335982   Bangalore                       M Chinnaswamy Stadium
1      335983  Chandigarh  Punjab Cricket Association Stadium, Mohali
2      335984       Delhi                            Feroz Shah Kotla
3      335985      Mumbai                            Wankhede Stadium
4      335986     Kolkata                                Eden Gardens
..        ...         ...                                         ...
512    829815   Hyderabad   Rajiv Gandhi International Stadium, Uppal
513    829817      Mumbai                            Wankhede Stadium
514    829819        Pune     Maharashtra Cricket Association Stadium
515    829821      Ranchi          JSCA International Stadium Complex
516    829823     Kolkata                                Eden Gardens

[517 rows x 3 columns]

In [15]:
q("""SELECT match_id,city,venue 
FROM matches 
where season >= 2015 OR city='Kolkata';""")

,match_id,city,venue
0,1082591,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,1082592,Pune,Maharashtra Cricket Association Stadium
2,1082593,Rajkot,Saurashtra Cricket Association Stadium
3,1082594,Indore,Holkar Cricket Stadium
4,1082595,Bengaluru,M.Chinnaswamy Stadium
...,...,...,...
789,1529282,Delhi,"Arun Jaitley Stadium, Delhi"
790,1529283,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
791,1529284,Mumbai,"Wankhede Stadium, Mumbai"
792,1529285,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
793,1529286,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [16]:
q("""SELECT match_id,city,venue 
FROM matches 
where season >= 2015 AND city='Kolkata';""")

    match_id     city                  venue
0     829705  Kolkata           Eden Gardens
1     829713  Kolkata           Eden Gardens
2     829723  Kolkata           Eden Gardens
3     829761  Kolkata           Eden Gardens
4     829781  Kolkata           Eden Gardens
..       ...      ...                    ...
59   1473494  Kolkata  Eden Gardens, Kolkata
60   1527679  Kolkata  Eden Gardens, Kolkata
61   1527685  Kolkata  Eden Gardens, Kolkata
62   1527688  Kolkata  Eden Gardens, Kolkata
63   1529271  Kolkata  Eden Gardens, Kolkata

[64 rows x 3 columns]

In [17]:
q("""SELECT match_Winner,season
FROM matches 
where season >= 2010 AND match_winner='Royal Challengers Bangalore';""")

                    match_winner season
0    Royal Challengers Bangalore   2010
1    Royal Challengers Bangalore   2010
2    Royal Challengers Bangalore   2010
3    Royal Challengers Bangalore   2010
4    Royal Challengers Bangalore   2010
..                           ...    ...
121  Royal Challengers Bangalore   2026
122  Royal Challengers Bangalore   2026
123  Royal Challengers Bangalore   2026
124  Royal Challengers Bangalore   2026
125  Royal Challengers Bangalore   2026

[126 rows x 2 columns]

In [18]:
q("""SELECT city,season
FROM matches 
where season >= 2016 OR city ='kolkata'
ORDER BY city ;""")

              city   season
0              NaN  2020/21
1              NaN  2020/21
2              NaN  2020/21
3              NaN  2020/21
4              NaN  2020/21
..             ...      ...
690  Visakhapatnam     2016
691  Visakhapatnam     2016
692  Visakhapatnam     2016
693  Visakhapatnam     2016
694  Visakhapatnam     2025

[695 rows x 2 columns]

In [19]:
q("""SELECT city,season
FROM matches 
where season >= 2016 OR city ='kolkata'
ORDER BY match_id DESC;""")

               city season
0            Jaipur   2026
1         Ahmedabad   2026
2            Mumbai   2026
3    New Chandigarh   2026
4             Delhi   2026
..              ...    ...
690         Kolkata   2016
691       Bangalore   2016
692      Chandigarh   2016
693         Kolkata   2016
694          Mumbai   2016

[695 rows x 2 columns]

In [20]:
q("""SELECT city,season
FROM matches 
where season >= 2016 OR city ='kolkata'
ORDER BY match_id ASC;""")

               city season
0            Mumbai   2016
1           Kolkata   2016
2        Chandigarh   2016
3         Bangalore   2016
4           Kolkata   2016
..              ...    ...
690           Delhi   2026
691  New Chandigarh   2026
692          Mumbai   2026
693       Ahmedabad   2026
694          Jaipur   2026

[695 rows x 2 columns]

In [21]:
q("""SELECT COUNT(*) FROM matches ;""")

   COUNT(*)
0      1212

In [22]:
q("""SELECT COUNT(*) AS matches FROM matches;""")

   matches
0     1212

In [23]:
q("""SELECT COUNT ( DISTINCT venue )AS venues FROM matches""")

   venues
0      59

In [24]:
q("""SELECT COUNT(*) AS matches FROM matches;""")

   matches
0     1212

In [25]:
q("""SELECT COUNT(*) AS venues FROM venues;""")

   venues
0      63

In [26]:
q("""SELECT COUNT(*) AS players FROM players;""")

   players
0      799

In [27]:
q("""SELECT COUNT(*) AS teams FROM teams;""")

   teams
0     16

In [28]:
q("""SELECT COUNT(*) AS deliveries FROM deliveries;""")

   deliveries
0      288226

In [29]:
q("""SELECT venue,count(*) AS matches
FROM matches
GROUP BY venue;""")

                                                venue  matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [30]:
q("""SELECT match_winner,COUNT(*) AS wins
FROM matches
GROUP BY match_winner
ORDER BY WINS DESC;""")

                   match_winner  wins
0                Mumbai Indians   155
1           Chennai Super Kings   146
2   Royal Challengers Bangalore   139
3         Kolkata Knight Riders   137
4           Sunrisers Hyderabad   132
5                  Punjab Kings   130
6                Delhi Capitals   126
7              Rajasthan Royals   125
8                Gujarat Titans    42
9          Lucknow Super Giants    33
10       Rising Pune Supergiant    15
11                Pune Warriors    13
12                Gujarat Lions    13
13         Kochi Tuskers Kerala     6

In [31]:
q("""SELECT match_winner,count(*) as winner
from matches
group by match_winner
having count (*)>100
order by winner desc;""")

                  match_winner  winner
0               Mumbai Indians     155
1          Chennai Super Kings     146
2  Royal Challengers Bangalore     139
3        Kolkata Knight Riders     137
4          Sunrisers Hyderabad     132
5                 Punjab Kings     130
6               Delhi Capitals     126
7             Rajasthan Royals     125

In [32]:
q("""SELECT bowler,count(*) as balls
from deliveries
group by bowler
having count (*)>=1000
order by balls desc;""")

          bowler  balls
0       R Ashwin   4868
1        B Kumar   4596
2      SP Narine   4586
3      RA Jadeja   4261
4      YS Chahal   4068
..           ...    ...
81      VR Aaron   1065
82    GJ Maxwell   1047
83  JR Hazlewood   1035
84    Noor Ahmad   1008
85       S Gopal   1000

[86 rows x 2 columns]

In [33]:
q("""SELECT count(*) as nullvalues
FROM matches
WHERE city is null;""")

   nullvalues
0          51

In [34]:
q("""SELECT count(*) as nullvalues
FROM matches
WHERE city is not null;""")

   nullvalues
0        1161

In [35]:
q("""SELECT count(*) as nullvalues
FROM matches
WHERE win_by_runs is not null;""")

   nullvalues
0         546

In [36]:
q("""SELECT match_winner,count(*) as win_by_runs
FROM matches
WHERE win_by_runs is NOT NULL
GROUP BY match_winner""")

                   match_winner  win_by_runs
0           Chennai Super Kings           75
1                Delhi Capitals           47
2                 Gujarat Lions            1
3                Gujarat Titans           16
4          Kochi Tuskers Kerala            2
5         Kolkata Knight Riders           57
6          Lucknow Super Giants           20
7                Mumbai Indians           77
8                 Pune Warriors            6
9                  Punjab Kings           57
10             Rajasthan Royals           48
11       Rising Pune Supergiant            7
12  Royal Challengers Bangalore           64
13          Sunrisers Hyderabad           69

In [37]:
q("""SELECT batter,bowler,is_wicket
FROM deliveries
WHERE is_wicket=1""")

           batter        bowler  is_wicket
0      SC Ganguly        Z Khan          1
1      RT Ponting     JH Kallis          1
2       DJ Hussey     AA Noffke          1
3        R Dravid      I Sharma          1
4         V Kohli      AB Dinda          1
...           ...           ...        ...
14335     R Parag      MA Starc          1
14336    SB Dubey   T Natarajan          1
14337  P Nissanka     RA Jadeja          1
14338      N Rana  TU Deshpande          1
14339    KL Rahul     JC Archer          1

[14340 rows x 3 columns]

In [38]:
q("""select trim   ('        virat kholi rcb       ');""")

  trim   ('        virat kholi rcb       ')
0                           virat kholi rcb

In [39]:
q("""select lower(batter)
from deliveries;""")

         lower(batter)
0       a ashish reddy
1       a ashish reddy
2       a ashish reddy
3       a ashish reddy
4       a ashish reddy
...                ...
288221          z khan
288222          z khan
288223          z khan
288224          z khan
288225          z khan

[288226 rows x 1 columns]

In [40]:
q("""select city, length(city)
from venues;""")

              city  length(city)
0        Bangalore           9.0
1        Hyderabad           9.0
2             Pune           4.0
3           Rajkot           6.0
4           Indore           6.0
..             ...           ...
58            Pune           4.0
59          Raipur           6.0
60          Ranchi           6.0
61  New Chandigarh          14.0
62  New Chandigarh          14.0

[63 rows x 2 columns]

In [41]:
q("""SELECT match_winner,
CASE WHEN win_by_runs is NULL
THEN 'win by wickets'
ELSE 'win by runs'
END AS win_type
from matches;""")

                     match_winner        win_type
0           Kolkata Knight Riders     win by runs
1             Sunrisers Hyderabad     win by runs
2          Rising Pune Supergiant  win by wickets
3           Kolkata Knight Riders  win by wickets
4                    Punjab Kings  win by wickets
...                           ...             ...
1207  Royal Challengers Bangalore  win by wickets
1208             Rajasthan Royals  win by wickets
1209          Sunrisers Hyderabad  win by wickets
1210               Gujarat Titans  win by wickets
1211               Delhi Capitals  win by wickets

[1212 rows x 2 columns]

In [42]:
q("""SELECT venue,count(*) as matches
from matches
group by venue;""")

                                                venue  matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [43]:
q("""SELECT venue,count(*) as matches
from matches
where venue='Buffalo Park' OR venue='Barabati Stadium'
group by venue;""")

              venue  matches
0  Barabati Stadium        7
1      Buffalo Park        3

In [44]:
q("""SELECT batter,count(*) as deliveries
from deliveries
group by batter;""")

             batter  deliveries
0    A Ashish Reddy         196
1          A Badoni         865
2        A Chandila           7
3          A Chopra          75
4       A Choudhary          20
..              ...         ...
722   Yashpal Singh          67
723     Younis Khan           7
724   Yudhvir Singh          16
725    Yuvraj Singh        2207
726          Z Khan         141

[727 rows x 2 columns]

In [45]:
q("""SELECT batter,count(*) as deliveries
from deliveries
group by batter
order by deliveries desc;""")

             batter  deliveries
0           V Kohli        6942
1         RG Sharma        5561
2          S Dhawan        5483
3         DA Warner        4849
4         AM Rahane        4259
..              ...         ...
722     Sunny Gupta           1
723          U Kaul           1
724  V Pratap Singh           1
725   Y Prithvi Raj           1
726      YA Abdulla           1

[727 rows x 2 columns]

In [46]:
q("""SELECT match_winner,
CASE WHEN win_by_runs>50
THEN 'High runs'
ELSE 'Low runs'
END AS runs
FROM matches;""")

                     match_winner       runs
0           Kolkata Knight Riders  High runs
1             Sunrisers Hyderabad   Low runs
2          Rising Pune Supergiant   Low runs
3           Kolkata Knight Riders   Low runs
4                    Punjab Kings   Low runs
...                           ...        ...
1207  Royal Challengers Bangalore   Low runs
1208             Rajasthan Royals   Low runs
1209          Sunrisers Hyderabad   Low runs
1210               Gujarat Titans   Low runs
1211               Delhi Capitals   Low runs

[1212 rows x 2 columns]

In [47]:

q("""SELECT m.match_id,m.venue,v.city
FROM matches m
JOIN venues v on m.venue=v.venue
LIMIT 10;""")

   match_id                                      venue       city
0    335982                      M Chinnaswamy Stadium  Bangalore
1   1082591  Rajiv Gandhi International Stadium, Uppal  Hyderabad
2   1082592    Maharashtra Cricket Association Stadium       Pune
3   1082593     Saurashtra Cricket Association Stadium     Rajkot
4   1082594                     Holkar Cricket Stadium     Indore
5   1082595                      M.Chinnaswamy Stadium  Bengaluru
6   1082596  Rajiv Gandhi International Stadium, Uppal  Hyderabad
7   1082597                           Wankhede Stadium     Mumbai
8   1082598                     Holkar Cricket Stadium     Indore
9   1082599    Maharashtra Cricket Association Stadium       Pune

In [48]:
q("""SELECT d.batter,p.bat_style
FROM deliveries AS d
JOIN players AS p ON p.player_name=d.batter;""")

            batter       bat_style
0       MN Samuels  Right hand Bat
1       MN Samuels  Right hand Bat
2       MN Samuels  Right hand Bat
3       MN Samuels  Right hand Bat
4       MN Samuels  Right hand Bat
...            ...             ...
288221      N Rana   Left hand Bat
288222      N Rana   Left hand Bat
288223      N Rana   Left hand Bat
288224   SU Parakh   Left hand Bat
288225   SU Parakh   Left hand Bat

[288226 rows x 2 columns]

In [49]:
q("""SELECT venue
FROM venues

EXCEPT
SELECT DISTINCT venue
FROM matches;""")

Empty DataFrame
Columns: [venue]
Index: []

In [50]:
q("""SELECT count(DISTINCT batter)
FROM deliveries
WHERE batter NOT IN (SELECT player_name FROM players)""")

   count(DISTINCT batter)
0                       0

In [51]:
q("""SELECT COUNT(*) AS TOTAL,
SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS Missing
FROM matches;""")

   TOTAL  Missing
0   1212       51

In [52]:
q("""SELECT COUNT(*) AS total,
SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS missing
from venues;""")

   total  missing
0     63        2

In [53]:
q("""SELECT COUNT(DISTINCT venue) as venues
FROM matches;""")

   venues
0      59

In [54]:
q("""SELECT COUNT(*) AS total,
SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS nullS,
SUM(CASE WHEN city ='' THEN 1 ELSE 0 END) AS  empty,
SUM(CASE WHEN TRIM(city)=''AND city=''THEN 1 ELSE 0 END) AS spaces
FROM matches;""")

   total  nullS  empty  spaces
0   1212     51      0       0

In [55]:
q("""select count (distinct
case when instr(venue,',')>0
then trim(substr(venue,1,instr(venue,',')-1))
else trim (venue)end) as after_coma
from matches;""")

   after_coma
0          42

In [56]:
q("""select count (distinct venue) as distinct_venue
from matches;""")

   distinct_venue
0              59

In [57]:
q("""select count(*) as rows,
count (distinct venue) as distinct_venues
from venues;""")

   rows  distinct_venues
0    63               59

In [58]:
q("""select venue,count(*) as n
from venues
group by venue
having count(*)>1;""")

                                               venue  n
0                 Dr DY Patil Sports Academy, Mumbai  2
1                Dubai International Cricket Stadium  2
2  Maharaja Yadavindra Singh International Cricke...  2
3                            Sharjah Cricket Stadium  2

In [59]:
q("""select team_name,
(select count(*) 
from matches m
where m.team1=t.team_name or m.team2=t.team_name) as played
from teams t
order by team_name;""")

                      team_name  played
0           Chennai Super Kings     260
1               Deccan Chargers       0
2                Delhi Capitals     276
3                 Gujarat Lions      30
4                Gujarat Titans      69
5          Kochi Tuskers Kerala      14
6         Kolkata Knight Riders     272
7          Lucknow Super Giants      66
8                Mumbai Indians     285
9                 Pune Warriors      46
10                 Punjab Kings     272
11             Rajasthan Royals     245
12       Rising Pune Supergiant      30
13      Rising Pune Supergiants       0
14  Royal Challengers Bangalore     279
15          Sunrisers Hyderabad     280

In [60]:
q("""select result,count(*) as n
from matches
group by result;""")

      result     n
0  no result     9
1        tie    16
2        win  1187